### ISSUE TITLE
Row highlighting

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#10]
Omnitable should be able to highlight rows for different reasons.

1. Clicking on a row (without clicking on a link or checkbox) we might want to highlight it in a color(?)
2. Selecting an item with the checkbox should also color the whole row in (another?) color?
3. Programmatically highlighting one or more affected rows according to a related component's actions / selected items

**Comment by plequang** [comment]
This issue should be clarified a bit I think.

Should highlighted rows be distinct from selected items ? Or should we have a property like `highlight-selected-items` to control that behavior.

Do we need single row highlighting ?

Also, currently the row templates are instantiated by cosmoz-grouped-list, which provide the following model to templates:
```
{
  selected: false, 
  item: {},
  folded: false, // for grow row
  expanded: false, // for item row
}
```

If we want to add `highlighted` to this model, I think we will need to update cosmoz-grouped-list, meaning highlighted rows should be handled in that component.

**Comment by JaySunSyn** [comment]
Did single row highlighting with this PR https://github.com/Neovici/cosmoz-grouped-list/pull/9

I could add multiple row highlighting either here or in grouped-list.

My first thought was, when a highlighted row gets selected, it might should get "de-highlighted". Rather than the other way around. But not sure about this.. Its like level 1, 2, 3 while level 2 is not 1 & 2 but only 2. It's not exactly like this herre but I guess you know what I mean.

**Comment by JaySunSyn** [comment]
Can be closed.
