### ISSUE TITLE
Avoid iron-list _increasePool lag on empty -> full

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#11]
Going from an empty omnitable to a filled one takes a long time, mainly because iron-list has to _increasePool until visible viewport is filled.

![increasepool](https://cloud.githubusercontent.com/assets/960553/21051210/76aceea0-be1f-11e6-9801-4f5f9041002b.png)

Can we pre-fill this with empty items on load to avoid this or otherwise fix this?
Is this solved in next-gen omnitable?

**Comment by plequang** [comment]
Trying to clarify a bit what's happening in cosmoz-omnitable.

Rendering cosmoz-omnitable is a 3 steps process, as shown in this timeline :

![image](https://cloud.githubusercontent.com/assets/5500311/21309553/12f0d6c0-c5df-11e6-96e9-164988702dc3.png)

Going from empty table to filled one takes time because `iron-list` has to stamp as much templates as needed to fill the viewport, and the template for each row is quite complex. In next-gen omnitable, each cell is rendered using a stamped template with `Polymer.Templatizer`, which is a bit more costly than previous version. 

If we look in detail at the timeline for steps 1 and 2, using `full-demo.html` :

![image](https://cloud.githubusercontent.com/assets/5500311/21312836/bae1e19e-c5ee-11e6-8c00-6bcda3f47c15.png)

Rendering an empty table takes no time, as no templates are stamped.

`cosmoz-grouped-list` introduced a new *warm up* feature, that allow to initialize the table with empty templates. Using this feature, the timeline is a bit different:

![image](https://cloud.githubusercontent.com/assets/5500311/21312938/2e514ad4-c5ef-11e6-8b96-bffa379be643.png)

With the *warm up* feature, `iron-list` is first filled with empty templates (`<div></div>`), and when real data is set, the templates are replaced with real ones.

As you can see, this does not change the total time spent in steps 1 and 2. 

I'm not sure there is a benefit in doing this.

I think the only way to reduce time spent in `_increasePool` is to reduce time used to stamp row templates, but don't know how to do that

PS: the timelines where generated using branch https://github.com/Neovici/cosmoz-omnitable/tree/column-rework

**Comment by nomego** [comment]
I don't feel like this is an issue any more.
