### ISSUE TITLE
Mobile Defect - Group on in Omnitable

### ISSUE THREAD

**Issue by SimonThunborg** [Neovici/cosmoz-omnitable#216]
Tested in Beta on mobile (iPhoneX, version 11.3.1).

When choosing "Group on" in the bottom bar the action bar appears.

I have not checked any of the invoices in Omnitable, so the action bar should not appear.

Found the defect in the following omnitables:
Invoice archive
Auto approved invoices
Open invoices

**Comment by megheaiulian** [comment]
Turns out that when opening the groupOn and sortOn dropdowns they are a bit bigger than the table omnitable content area and they force about 10px scrolling  making the `cosmoz-bottom-bar` that is translated outside of omnitable show up. Trying to fix this by catching the open and close events of the dropdowns and adjusting the height.
