### ISSUE TITLE
Datetime/timestamp column

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-omnitable#22]
For things like history and detailed information about events, we need a column that also displays the time of the date/timestamp.
In earlier omnitable versions, the date-column would detect if time was something else than 00:00:00 and display it then, but it would be easier, more declarative and faster to just do a new column for this now.

**Comment by JaySunSyn** [comment]
Would you also like to filter/sort/group on this field or is it just a "detail" of the date field?

If it is only for displaying more details, setting the property `user-format="mm:ss"` on `cosmoz-omnitable-column-date` will make it. Additionally we should integrate something like `hideFilter`
```
<cosmoz-omnitable-column-date title="Date detail" value-path="date" user-format="mm:ss" hide-filter>
```

**Comment by nomego** [comment]
It should be another type of column to allow filtering and sorting, not sure how much sense grouping will be but we'll get it anyway :)

**Comment by JaySunSyn** [comment]
In `cosmoz-omnitable.js` we have a function `_getSortOnColumn`to retrieve a column based on the `value-path`. (see https://github.com/Neovici/cosmoz-omnitable/blob/master/cosmoz-omnitable.js#L492) (same with grouping.)

```
                    _getSortOnColumn: function () {
			var col;

			if (!this.sortOn || !this.sortOn.valuePath) {
				return;
			}
			this.columns.some(function (column) {
				if (column.sortOn === this.sortOn.valuePath) {
					col = column;
					return true;
				}
			}, this);
			return col;
		},
```
The first match gets taken. This requires value-path to be unique among all columns. I run into a  problem here while creating a time column which has the same `value-path`as the date column `date`. 

The problem only occurs because we want to support a sort value change from outside of the element. If the sort value change happens from the sort dropdown, I can get the column reference from the event and store it in the `sortOn` object. (https://github.com/Neovici/cosmoz-omnitable/blob/master/cosmoz-omnitable.js#L972)

We could include a unique "name" or "id" attribute for columns which we could use when referencing a specific column for sorting. 

What do you think @plequang @nomego ?

**Comment by nomego** [comment]
Well first of all it's a rare enough scenario that we haven't really run into it yet.

But yes, I had a similar use case with `enabledColumns` so columns now have a `name` property like you describe. (https://github.com/Neovici/cosmoz-omnitable/blob/master/cosmoz-omnitable-column-behavior.html#L66)

However, we use this quite extensively in the app so I think that function should prioritize `name` but fall back to `valuePath` with a `console.warn()`.

Also we can now use es6 stuff so feel free to go from `some()` to `find()` :)

Objections @plequang ?

**Comment by plequang** [comment]
Sorry, bit late in commenting that.
Meanwhile columns name have been implemented, so no objections 😄 
No objections for `some()` and `find()` either.

**Comment by JaySunSyn** [comment]
@nomego can be closed.
PR https://github.com/Neovici/cosmoz-omnitable/pull/40
